### ISSUE TITLE
Problem with SetFavoritePokemonMessage

### ISSUE THREAD

**Issue by BornSupercharged** [johnduhart/POGOProtos-dotnet#4]
This works fine:
message {{ "pokemonId": "123", "nickname": "My_Pinsir" }}   Google.Protobuf.IMessage {POGOProtos.Networking.Requests.Messages.NicknamePokemonMessage}

But this does not:
message {{ "pokemonId": "123", "isFavorite": true }}    Google.Protobuf.IMessage {POGOProtos.Networking.Requests.Messages.SetFavoritePokemonMessage}

It always sends back:
parsedPayload    {{ "result": "ERROR_POKEMON_NOT_FOUND" }}    POGOProtos.Networking.Responses.SetFavoritePokemonResponse

**Comment by johnduhart** [comment]
You're probably better off asking on the [main proto project](https://github.com/AeonLucid/POGOProtos), it might be an issue with the definitions.

**Comment by BornSupercharged** [comment]
Thanks, I've fixed it and submitted a PR
https://github.com/AeonLucid/POGOProtos/pull/126
